import type { Metadata } from 'next';
import './globals.css';
import BottomNav from './components/bottom-nav/bottomNav';

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body>
				{children}
				<BottomNav />
			</body>
		</html>
	);
}
